sonar.projectKey=bithyve_bitcoin-keeper
sonar.organization=bithyve

# The test job produces this report; the analysis job downloads it unchanged.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true

sonar.coverage.exclusions=**/android/**/*.*,**/ios/**/*.* 
sonar.exclusions=**/android/**/*.*,**/ios/**/*.* 

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
