name: CI

on:
  push:
    branches:
      - sprint
      - dev
      - main
  pull_request:
    branches:
      - sprint
      - dev
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Run lint
        run: npm run lint

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: npm run test
